version: '3'
services:
  app:
    build: ./
    image: my-blog:latest
    volumes:
      - /root/programming_note:/root/programming_note
    environment:
      - GO_ENV=prod
    ports:
      - 7000:8000
    restart: always
