version: '3'
services:
  app:
    build: ./
    image: my-blog:latest
    volumes:
      - /Users/liqiang/Documents/personal/code/programming_note:/root/programming_note
    environment:
      - GO_ENV=prod
    ports:
      - 127.0.0.1:7000:8000
    restart: always
