version: '3'
services:
  app:
    build: ./
    image: go_blog:latest
    volumes:
      - ${blog_path}:/root/programming_note
    environment:
      - GO_ENV=prod
    ports:
      - 7000:7000
    restart: always
